/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chip: typeof import('primevue/chip')['default']
    ContactSection: typeof import('./src/components/home-view/ContactSection.vue')['default']
    ContectSection: typeof import('./src/components/home-view/ContectSection.vue')['default']
    CookieMsgCard: typeof import('./src/components/CookieMsgCard.vue')['default']
    copy: typeof import('./src/components/home-view/ProductsSection copy.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    FeaturesSection: typeof import('./src/components/home-view/FeaturesSection.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HeroSection: typeof import('./src/components/home-view/HeroSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProductsSectiom: typeof import('./src/components/home-view/ProductsSectiom.vue')['default']
    ProductsSection: typeof import('./src/components/home-view/ProductsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToolsSection: typeof import('./src/components/home-view/ToolsSection.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
